arch = [
  "intel-ucode",
  "s3cmd",
  "slack-desktop",
  "borgmatic",
  "intel-undervolt",
  "pam-u2f",
  "pam_mount",
  "yubikey-full-disk-encryption",
  "lastpass-cli",
  "tekton-cli",
  "azure-cli",
  "efitools",
  "sbctl",
  "sof-firmware",
  "debootstrap",
  "ubuntu-keyring",
]
