arch = [
    "libinput-gestures",
    "mplus-font",
    "numix-circle-icon-theme-git",
    "raw-thumbnailer",
    "ttf-material-design-iconic-font",
    "ttf-meslo",
    "numix-gtk-theme",
    "paper-gtk-theme-git",
    "autorestic-bin",
]
