arch = [
    "libinput-gestures",
    "numix-circle-icon-theme-git",
    "raw-thumbnailer",
    "ttf-material-design-iconic-font",
    "ttf-meslo",
    "numix-gtk-theme",
    "paper-gtk-theme-git",
    "autorestic-bin",
    "nordic-theme",
    "ttf-ms-fonts",
    "clipit-git",
    "localsend-bin",
    "vial-appimage",
]
