arch = [
  "age",
  "cilium-cli",
  "clusterctl-bin",
  "flux-bin",
  "helm",
  "kind-bin",
  "krew",
  "kubectx",
  "kubeseal",
  "kustomize",
  "linkerd",
  "sops",
  "stern-bin",
  "talosctl",
  "kubeswitch-bin",
  "helm-diff",
  "hubble-bin",
  "jsonnet",
  "kube-linter",
  "kubeval-bin",
  "vcluster-bin",
  "sonar-bin",
  "cfssl",
  "pwru",
  "dyff-bin",
  "sonar-bin"
]
