arch_package_manager = "paru"
disabled_backends = ["apt", "brew", "cargo", "dnf", "flatpak", "pipx", "rustup", "snap", "winget", "xbps"]

hostname_groups_enabled = true

[hostname_groups]
'phoenix.analbeard.com' = ["audio", "base", "desktop", "development", "display", "kubernetes", "laptop", "wireless", "phoenix"]
'cheyenne.analbeard.com' = ["base", "desktop", "display", "laptop", "wireless", "temp"]
#'cheyenne.analbeard.com' = ["audio", "base", "desktop", "development", "display", "kubernetes", "laptop", "wireless", "cheyenne"]
