arch_package_manager = "paru"
disabled_backends = ["apt", "brew", "cargo", "dnf", "flatpak", "pipx", "rustup", "snap", "winget", "xbps"]

hostname_groups_enabled = true

[hostname_groups]
'phoenix.analbeard.com' = [
    "audio",
    "audio-aur",
    "base",
    "desktop",
    "desktop-aur",
    "development",
    "development-aur",
    "display",
    "kubernetes",
    "kubernetes-aur",
    "laptop",
    "wireless",
    "phoenix"
]
'cheyenne.analbeard.com' = [
    "audio",
    "audio-aur",
    "base",
    "desktop",
    "desktop-aur",
    "development",
    "development-aur",
    "display",
    "kubernetes",
    "kubernetes-aur",
    "laptop",
    "wireless",
    "cheyenne",
    "cheyenne-aur",
]
