section: screens
	olympia:
		halfDuplexCapsLock = false
		halfDuplexNumLock = false
		halfDuplexScrollLock = false
		xtestIsXineramaUnaware = false
		preserveFocus = false
		switchCorners = none
		switchCornerSize = 0
	cheyenne:
		halfDuplexCapsLock = false
		halfDuplexNumLock = false
		halfDuplexScrollLock = false
		xtestIsXineramaUnaware = false
		preserveFocus = false
		switchCorners = none
		switchCornerSize = 0
end

section: aliases
	cheyenne:
		cheyenne.analbeard.com
    olympia:
        olympia.a7d.dev
end

section: links
    cheyenne:
        left = olympia.a7d.dev
    olympia:
        right = cheyenne.analbeard.com
end

section: options
	relativeMouseMoves = false
	win32KeepForeground = false
	disableLockToScreen = false
	clipboardSharing = true
	clipboardSharingSize = 3072
	switchCorners = none
	switchCornerSize = 0
end
